### PR TITLE
Compatibility with transformers-0.6

### PR DESCRIPTION
**Pull request by TeofilC**
This will be required for GHC-9.6 compat

### CODE REVIEW

**Comment by TeofilC** [comment]
No rush to review this @thomasjm but I noticed that you don't "watch" this repo so wanted to make sure you got a notification.

**Comment by thomasjm** [comment]
Oh, it's you again! I was just tidying up my old notifications and noticed I hadn't responded to this. The current status is that we're working on transferring the webdriver repo to a GitHub organization, and once that's ready we can start closing issues and stuff over there.

**Comment by TeofilC** [comment]
Sounds good!

**Comment by thomasjm** [comment]
Hey, could I trouble you to re-open this against https://github.com/haskell-webdriver/haskell-webdriver ?

**Comment by TeofilC** [comment]
No worries done: https://github.com/haskell-webdriver/haskell-webdriver/pull/192

**Pull request closed without merging**
